### PR TITLE
Create env prod

### LINKED ISSUE #44: create enviroment vars to produccion

### PR DESCRIPTION
**Pull request by juanpms2**
is fixed #44

### CODE REVIEW

**Comment by juanpms2** [comment]
add new commits but not resolve the problem on production. Master and players comunication conflict at send info.

**Comment by brauliodiez** [comment]
OOops we have to fix merge conflicts here, catch you tomorrow to talk about this

**Comment by delamux** [comment]
I'm taking a look right now and I will have conflicts with my branch, I changed the backend folder structure, but is not too much.

**Comment by brauliodiez** [comment]
I think this is outdated and a solution is already in master, thanks for the good work, going to close this PR.

We are almost there :)

**Pull request closed without merging**
